apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd-applications
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: argocd-applications
  name: awx-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: awx-operator
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/awx-operator-config.git
      targetRevision: HEAD
    # - chart: awx-operator
    #   helm:
    #     releaseName: awx-operator
    #     valuesObject:
    #       AWX:
    #         enabled: false
    #   ref: helm
    #   repoURL: https://ansible-community.github.io/awx-operator-helm/
    #   targetRevision: 3.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
