apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: freeipa
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: freeipa-config
  name: freeipa
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: freeipa
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/freeipa-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - ServerSideApply=true
