apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd-applications
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: argocd-applications
  name: local-storage
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: local-storage
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/local-storage-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  # ignoreDifferences:
  #   - group: '*'
  #     kind: '*'
  #     managedFieldsManagers:
  #       - vault-k8s
