apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd-applications
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: argocd-applications
  name: rook
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: rook
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/rook-config.git
      targetRevision: HEAD
    - chart: rook
      helm:
        releaseName: rook
        valuesObject: {}
      ref: helm
      repoURL: https://charts.rook.io/release
      targetRevision: v1.18.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  # ignoreDifferences:
  #   - group: '*'
  #     kind: '*'
  #     managedFieldsManagers:
  #       - vault-k8s
