apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd-applications
    managedBy: argocd
    managementCodeGroup: chrismlee42
    managementCodeProject: argocd-applications
  name: rook
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: rook
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/rook-config.git
      targetRevision: HEAD
    # - chart: rook
    #   helm:
    #     releaseName: rook
    #     valuesObject:
    #       csi:
    #         # -- CEPH CSI RBD provisioner resource requirement list
    #         # csi-omap-generator resources will be applied only if `enableOMAPGenerator` is set to `true`
    #         # @default -- see values.yaml
    #         csiRBDProvisionerResource: |
    #           - name : csi-provisioner
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-resizer
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-attacher
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-snapshotter
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-rbdplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 100m
    #                 memory: 512Mi
    #           - name : csi-omap-generator
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #           - name : liveness-prometheus
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 50m
    #                 memory: 128Mi
    #         # -- CEPH CSI RBD plugin resource requirement list
    #         # @default -- see values.yaml
    #         csiRBDPluginResource: |
    #           - name : driver-registrar
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 50m
    #                 memory: 128Mi
    #           - name : csi-rbdplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #           - name : liveness-prometheus
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 50m
    #                 memory: 128Mi
    #         # -- CEPH CSI CephFS provisioner resource requirement list
    #         # @default -- see values.yaml
    #         csiCephFSProvisionerResource: |
    #           - name : csi-provisioner
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-resizer
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-attacher
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-snapshotter
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-cephfsplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #           - name : liveness-prometheus
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 50m
    #                 memory: 128Mi
    #         # -- CEPH CSI CephFS plugin resource requirement list
    #         # @default -- see values.yaml
    #         csiCephFSPluginResource: |
    #           - name : driver-registrar
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 50m
    #                 memory: 128Mi
    #           - name : csi-cephfsplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #           - name : liveness-prometheus
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 memory: 128Mi
    #                 cpu: 50m
    #         # -- CEPH CSI NFS provisioner resource requirement list
    #         # @default -- see values.yaml
    #         csiNFSProvisionerResource: |
    #           - name : csi-provisioner
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 cpu: 100m
    #                 memory: 128Mi
    #           - name : csi-nfsplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #           - name : csi-attacher
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #         # -- CEPH CSI NFS plugin resource requirement list
    #         # @default -- see values.yaml
    #         csiNFSPluginResource: |
    #           - name : driver-registrar
    #             resource:
    #               limits:
    #                 memory: 256Mi
    #               requests:
    #                 memory: 128Mi
    #                 cpu: 50m
    #           - name : csi-nfsplugin
    #             resource:
    #               limits:
    #                 memory: 1Gi
    #               requests:
    #                 cpu: 250m
    #                 memory: 512Mi
    #       # discover:
    #       #   # -- Add resources to discover daemon pods
    #       #   resources:
    #       #     - limits:
    #       #         memory: 512Mi
    #       #     - requests:
    #       #         cpu: 100m
    #       #         memory: 128Mi
    #       monitoring:
    #         # -- Enable monitoring. Requires Prometheus to be pre-installed.
    #         # Enabling will also create RBAC rules to allow Operator to create ServiceMonitors
    #         enabled: true
    #       # -- Pod resource requests & limits
    #       resources:
    #         limits:
    #           cpu: 4
    #           memory: 512Mi
    #         requests:
    #           cpu: 200m
    #           memory: 128Mi
    #       # -- If true, scale down the rook operator.
    #       # This is useful for administrative actions where the rook operator must be scaled down, while using gitops style tooling
    #       # to deploy your helm charts.
    #       # scaleDownOperator: true
    #   ref: helm
    #   repoURL: https://charts.rook.io/release
    #   targetRevision: v1.18.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - vault-k8s
